# Generated by Django 5.0.4 on 2024-04-27 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_counter', models.IntegerField(default=7)),
                ('a', models.FloatField(default=1)),
                ('aa', models.FloatField(default=1)),
                ('i', models.FloatField(default=1)),
                ('ii', models.FloatField(default=1)),
                ('u', models.FloatField(default=1)),
                ('uu', models.FloatField(default=1)),
                ('r', models.FloatField(default=1)),
                ('e', models.FloatField(default=0)),
                ('ee', models.FloatField(default=0)),
                ('ai', models.FloatField(default=0)),
                ('o', models.FloatField(default=0)),
                ('oo', models.FloatField(default=0)),
                ('au', models.FloatField(default=0)),
                ('am', models.FloatField(default=0)),
                ('ah', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
