# Generated by Django 5.0.4 on 2024-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='flashcard_allowed_levels',
            field=models.IntegerField(default=1),
        ),
    ]
