# Generated by Django 5.0.4 on 2024-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userstatsmodel_flashcard_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatsmodel',
            name='ordering_alphabet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='ordering_image',
            field=models.IntegerField(default=0),
        ),
    ]
