# Generated by Django 5.0.4 on 2024-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userstatsmodel_quiz_1_userstatsmodel_quiz_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatsmodel',
            name='ccha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='cha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='da',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='dda',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='ddha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='dha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='ggha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='gha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='ja',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='jja',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='ka',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='kka',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='na',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='nga',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='nna',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='nnja',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='ta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='tha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='tta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='ttha',
            field=models.FloatField(default=0),
        ),
    ]
